version: "3.3"
services:
    web:
        build:
            context: ./app/web
        volumes:
            - ./app/web/src:/var/www/html
        ports:
            - "8000:80"
        depends_on:
            - db

    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=p4ssw0rd
            - MYSQL_DATABASE=database
        volumes:
            - ./app/db:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"

